### ISSUE TITLE
Scene-guided occlusion identification

### ISSUE THREAD

**Issue by yixchen** [zju3dv/object_nerf#10]
Hi,

Thanks for the paper and the code contribution. Nice work!

One question: could you please point out the code reference for the "scene-guided occlusion identification (scene guidance + 3D guard mask)" and how they affect the loss backpropagation? Thanks again.

**Comment by ybbbbt** [comment]
Hi, yixchen,

The code snippet related to 3D guard mask is:

https://github.com/zju3dv/object_nerf/blob/e8b1a7a5ab0596babdf4400a9e8908f1bfdcf990/models/rendering.py#L192-L202

As for the scene guidence, since we always use `weights_coarse` for both scene and object sampling, it directly inherits sampling distributions from the scene branch:

https://github.com/zju3dv/object_nerf/blob/e8b1a7a5ab0596babdf4400a9e8908f1bfdcf990/models/rendering.py#L305-L310

**Comment by yixchen** [comment]
Hi, thanks for the prompt reply. I will look into them.
